// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Pipeline>> githubListRuns({
  required String token,
  required String fullName,
}) => RustLib.instance.api.crateApiCicdGithubListRuns(
  token: token,
  fullName: fullName,
);

Future<void> githubRetryRun({
  required String token,
  required String fullName,
  required BigInt runId,
}) => RustLib.instance.api.crateApiCicdGithubRetryRun(
  token: token,
  fullName: fullName,
  runId: runId,
);
