// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Issue>> githubListIssues({
  required String token,
  required String fullName,
  String? state,
}) => RustLib.instance.api.crateApiIssuesGithubListIssues(
  token: token,
  fullName: fullName,
  state: state,
);
