// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Issue>> githubListIssues({
  required String token,
  required String fullName,
  String? state,
}) => RustLib.instance.api.crateApiIssuesGithubListIssues(
  token: token,
  fullName: fullName,
  state: state,
);

Future<Issue> githubGetIssue({
  required String token,
  required String fullName,
  required BigInt number,
}) => RustLib.instance.api.crateApiIssuesGithubGetIssue(
  token: token,
  fullName: fullName,
  number: number,
);

Future<List<IssueComment>> githubListComments({
  required String token,
  required String fullName,
  required BigInt number,
}) => RustLib.instance.api.crateApiIssuesGithubListComments(
  token: token,
  fullName: fullName,
  number: number,
);

Future<Issue> githubCreateIssue({
  required String token,
  required String fullName,
  required String title,
  String? body,
}) => RustLib.instance.api.crateApiIssuesGithubCreateIssue(
  token: token,
  fullName: fullName,
  title: title,
  body: body,
);

Future<Issue> githubCloseIssue({
  required String token,
  required String fullName,
  required BigInt number,
}) => RustLib.instance.api.crateApiIssuesGithubCloseIssue(
  token: token,
  fullName: fullName,
  number: number,
);

Future<Issue> githubReopenIssue({
  required String token,
  required String fullName,
  required BigInt number,
}) => RustLib.instance.api.crateApiIssuesGithubReopenIssue(
  token: token,
  fullName: fullName,
  number: number,
);

Future<IssueComment> githubCreateComment({
  required String token,
  required String fullName,
  required BigInt number,
  required String body,
}) => RustLib.instance.api.crateApiIssuesGithubCreateComment(
  token: token,
  fullName: fullName,
  number: number,
  body: body,
);
