// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `validate_full_name`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

@freezed
sealed class CodeportError with _$CodeportError implements FrbException {
  const CodeportError._();

  const factory CodeportError.auth() = CodeportError_Auth;
  const factory CodeportError.network(String field0) = CodeportError_Network;
  const factory CodeportError.rateLimited({required String resetAt}) =
      CodeportError_RateLimited;
  const factory CodeportError.notFound() = CodeportError_NotFound;
  const factory CodeportError.validation(String field0) =
      CodeportError_Validation;
}

class Issue {
  final BigInt id;
  final BigInt number;
  final String title;
  final IssueState state;
  final List<String> labels;

  const Issue({
    required this.id,
    required this.number,
    required this.title,
    required this.state,
    required this.labels,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      number.hashCode ^
      title.hashCode ^
      state.hashCode ^
      labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Issue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          number == other.number &&
          title == other.title &&
          state == other.state &&
          labels == other.labels;
}

enum IssueState { open, closed }

class Pipeline {
  final BigInt id;
  final PipelineStatus status;
  final PipelineConclusion? conclusion;
  final BigInt runNumber;

  const Pipeline({
    required this.id,
    required this.status,
    this.conclusion,
    required this.runNumber,
  });

  @override
  int get hashCode =>
      id.hashCode ^ status.hashCode ^ conclusion.hashCode ^ runNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pipeline &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status &&
          conclusion == other.conclusion &&
          runNumber == other.runNumber;
}

enum PipelineConclusion { success, failure, cancelled }

enum PipelineStatus { queued, inProgress, completed }

class Repo {
  final BigInt id;
  final String fullName;
  final bool private;
  final BigInt stars;
  final String defaultBranch;

  const Repo({
    required this.id,
    required this.fullName,
    required this.private,
    required this.stars,
    required this.defaultBranch,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      fullName.hashCode ^
      private.hashCode ^
      stars.hashCode ^
      defaultBranch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Repo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fullName == other.fullName &&
          private == other.private &&
          stars == other.stars &&
          defaultBranch == other.defaultBranch;
}

class RepoPage {
  final List<Repo> repos;
  final int? nextPage;

  const RepoPage({required this.repos, this.nextPage});

  @override
  int get hashCode => repos.hashCode ^ nextPage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoPage &&
          runtimeType == other.runtimeType &&
          repos == other.repos &&
          nextPage == other.nextPage;
}
