// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/auth.dart';
import 'api/cicd.dart';
import 'api/issues.dart';
import 'api/repositories.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 49495023;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_codeport',
        ioDirectory: '../../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Issue> crateApiIssuesGithubCloseIssue({
    required String token,
    required String fullName,
    required BigInt number,
  });

  Future<IssueComment> crateApiIssuesGithubCreateComment({
    required String token,
    required String fullName,
    required BigInt number,
    required String body,
  });

  Future<Issue> crateApiIssuesGithubCreateIssue({
    required String token,
    required String fullName,
    required String title,
    String? body,
  });

  Future<Issue> crateApiIssuesGithubGetIssue({
    required String token,
    required String fullName,
    required BigInt number,
  });

  Future<Repo> crateApiRepositoriesGithubGetRepo({
    required String token,
    required String fullName,
  });

  Future<Pipeline> crateApiCicdGithubGetRun({
    required String token,
    required String fullName,
    required BigInt runId,
  });

  Future<List<IssueComment>> crateApiIssuesGithubListComments({
    required String token,
    required String fullName,
    required BigInt number,
  });

  Future<List<Commit>> crateApiRepositoriesGithubListCommits({
    required String token,
    required String fullName,
  });

  Future<List<Issue>> crateApiIssuesGithubListIssues({
    required String token,
    required String fullName,
    String? state,
  });

  Future<List<CiJob>> crateApiCicdGithubListJobs({
    required String token,
    required String fullName,
    required BigInt runId,
  });

  Future<RepoPage> crateApiRepositoriesGithubListRepos({
    required String token,
    required int page,
  });

  Future<List<Pipeline>> crateApiCicdGithubListRuns({
    required String token,
    required String fullName,
  });

  Future<Issue> crateApiIssuesGithubReopenIssue({
    required String token,
    required String fullName,
    required BigInt number,
  });

  Future<void> crateApiCicdGithubRetryRun({
    required String token,
    required String fullName,
    required BigInt runId,
  });

  Stream<Pipeline> crateApiCicdGithubWatchRun({
    required String token,
    required String fullName,
    required BigInt runId,
  });

  Future<void> crateApiAuthValidateToken({required String token});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Issue> crateApiIssuesGithubCloseIssue({
    required String token,
    required String fullName,
    required BigInt number,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(number, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubCloseIssueConstMeta,
        argValues: [token, fullName, number],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubCloseIssueConstMeta =>
      const TaskConstMeta(
        debugName: "github_close_issue",
        argNames: ["token", "fullName", "number"],
      );

  @override
  Future<IssueComment> crateApiIssuesGithubCreateComment({
    required String token,
    required String fullName,
    required BigInt number,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(number, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issue_comment,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubCreateCommentConstMeta,
        argValues: [token, fullName, number, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubCreateCommentConstMeta =>
      const TaskConstMeta(
        debugName: "github_create_comment",
        argNames: ["token", "fullName", "number", "body"],
      );

  @override
  Future<Issue> crateApiIssuesGithubCreateIssue({
    required String token,
    required String fullName,
    required String title,
    String? body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_String(title, serializer);
          sse_encode_opt_String(body, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubCreateIssueConstMeta,
        argValues: [token, fullName, title, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubCreateIssueConstMeta =>
      const TaskConstMeta(
        debugName: "github_create_issue",
        argNames: ["token", "fullName", "title", "body"],
      );

  @override
  Future<Issue> crateApiIssuesGithubGetIssue({
    required String token,
    required String fullName,
    required BigInt number,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(number, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubGetIssueConstMeta,
        argValues: [token, fullName, number],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubGetIssueConstMeta =>
      const TaskConstMeta(
        debugName: "github_get_issue",
        argNames: ["token", "fullName", "number"],
      );

  @override
  Future<Repo> crateApiRepositoriesGithubGetRepo({
    required String token,
    required String fullName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_repo,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiRepositoriesGithubGetRepoConstMeta,
        argValues: [token, fullName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRepositoriesGithubGetRepoConstMeta =>
      const TaskConstMeta(
        debugName: "github_get_repo",
        argNames: ["token", "fullName"],
      );

  @override
  Future<Pipeline> crateApiCicdGithubGetRun({
    required String token,
    required String fullName,
    required BigInt runId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubGetRunConstMeta,
        argValues: [token, fullName, runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubGetRunConstMeta => const TaskConstMeta(
    debugName: "github_get_run",
    argNames: ["token", "fullName", "runId"],
  );

  @override
  Future<List<IssueComment>> crateApiIssuesGithubListComments({
    required String token,
    required String fullName,
    required BigInt number,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(number, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_issue_comment,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubListCommentsConstMeta,
        argValues: [token, fullName, number],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubListCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_comments",
        argNames: ["token", "fullName", "number"],
      );

  @override
  Future<List<Commit>> crateApiRepositoriesGithubListCommits({
    required String token,
    required String fullName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_commit,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiRepositoriesGithubListCommitsConstMeta,
        argValues: [token, fullName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRepositoriesGithubListCommitsConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_commits",
        argNames: ["token", "fullName"],
      );

  @override
  Future<List<Issue>> crateApiIssuesGithubListIssues({
    required String token,
    required String fullName,
    String? state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_opt_String(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubListIssuesConstMeta,
        argValues: [token, fullName, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubListIssuesConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_issues",
        argNames: ["token", "fullName", "state"],
      );

  @override
  Future<List<CiJob>> crateApiCicdGithubListJobs({
    required String token,
    required String fullName,
    required BigInt runId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ci_job,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubListJobsConstMeta,
        argValues: [token, fullName, runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubListJobsConstMeta => const TaskConstMeta(
    debugName: "github_list_jobs",
    argNames: ["token", "fullName", "runId"],
  );

  @override
  Future<RepoPage> crateApiRepositoriesGithubListRepos({
    required String token,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_repo_page,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiRepositoriesGithubListReposConstMeta,
        argValues: [token, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRepositoriesGithubListReposConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_repos",
        argNames: ["token", "page"],
      );

  @override
  Future<List<Pipeline>> crateApiCicdGithubListRuns({
    required String token,
    required String fullName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pipeline,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubListRunsConstMeta,
        argValues: [token, fullName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubListRunsConstMeta => const TaskConstMeta(
    debugName: "github_list_runs",
    argNames: ["token", "fullName"],
  );

  @override
  Future<Issue> crateApiIssuesGithubReopenIssue({
    required String token,
    required String fullName,
    required BigInt number,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(number, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubReopenIssueConstMeta,
        argValues: [token, fullName, number],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubReopenIssueConstMeta =>
      const TaskConstMeta(
        debugName: "github_reopen_issue",
        argNames: ["token", "fullName", "number"],
      );

  @override
  Future<void> crateApiCicdGithubRetryRun({
    required String token,
    required String fullName,
    required BigInt runId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_u_64(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubRetryRunConstMeta,
        argValues: [token, fullName, runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubRetryRunConstMeta => const TaskConstMeta(
    debugName: "github_retry_run",
    argNames: ["token", "fullName", "runId"],
  );

  @override
  Stream<Pipeline> crateApiCicdGithubWatchRun({
    required String token,
    required String fullName,
    required BigInt runId,
  }) {
    final sink = RustStreamSink<Pipeline>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_pipeline_Sse(sink, serializer);
            sse_encode_String(token, serializer);
            sse_encode_String(fullName, serializer);
            sse_encode_u_64(runId, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_codeport_error,
          ),
          constMeta: kCrateApiCicdGithubWatchRunConstMeta,
          argValues: [sink, token, fullName, runId],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiCicdGithubWatchRunConstMeta => const TaskConstMeta(
    debugName: "github_watch_run",
    argNames: ["sink", "token", "fullName", "runId"],
  );

  @override
  Future<void> crateApiAuthValidateToken({required String token}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiAuthValidateTokenConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthValidateTokenConstMeta =>
      const TaskConstMeta(debugName: "validate_token", argNames: ["token"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Pipeline> dco_decode_StreamSink_pipeline_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PipelineConclusion dco_decode_box_autoadd_pipeline_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_conclusion(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CiJob dco_decode_ci_job(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CiJob(
      id: dco_decode_u_64(arr[0]),
      name: dco_decode_String(arr[1]),
      status: dco_decode_pipeline_status(arr[2]),
      conclusion: dco_decode_opt_box_autoadd_pipeline_conclusion(arr[3]),
    );
  }

  @protected
  CodeportError dco_decode_codeport_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CodeportError_Auth();
      case 1:
        return CodeportError_Network(dco_decode_String(raw[1]));
      case 2:
        return CodeportError_RateLimited(resetAt: dco_decode_String(raw[1]));
      case 3:
        return CodeportError_NotFound();
      case 4:
        return CodeportError_Validation(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Commit dco_decode_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Commit(
      sha: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Issue dco_decode_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Issue(
      id: dco_decode_u_64(arr[0]),
      number: dco_decode_u_64(arr[1]),
      title: dco_decode_String(arr[2]),
      state: dco_decode_issue_state(arr[3]),
      labels: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  IssueComment dco_decode_issue_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IssueComment(
      id: dco_decode_u_64(arr[0]),
      body: dco_decode_String(arr[1]),
      author: dco_decode_String(arr[2]),
    );
  }

  @protected
  IssueState dco_decode_issue_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IssueState.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CiJob> dco_decode_list_ci_job(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ci_job).toList();
  }

  @protected
  List<Commit> dco_decode_list_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_commit).toList();
  }

  @protected
  List<Issue> dco_decode_list_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_issue).toList();
  }

  @protected
  List<IssueComment> dco_decode_list_issue_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_issue_comment).toList();
  }

  @protected
  List<Pipeline> dco_decode_list_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Repo> dco_decode_list_repo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_repo).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PipelineConclusion? dco_decode_opt_box_autoadd_pipeline_conclusion(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pipeline_conclusion(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Pipeline dco_decode_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Pipeline(
      id: dco_decode_u_64(arr[0]),
      status: dco_decode_pipeline_status(arr[1]),
      conclusion: dco_decode_opt_box_autoadd_pipeline_conclusion(arr[2]),
      runNumber: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  PipelineConclusion dco_decode_pipeline_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PipelineConclusion.values[raw as int];
  }

  @protected
  PipelineStatus dco_decode_pipeline_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PipelineStatus.values[raw as int];
  }

  @protected
  Repo dco_decode_repo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Repo(
      id: dco_decode_u_64(arr[0]),
      fullName: dco_decode_String(arr[1]),
      private: dco_decode_bool(arr[2]),
      stars: dco_decode_u_64(arr[3]),
      defaultBranch: dco_decode_String(arr[4]),
    );
  }

  @protected
  RepoPage dco_decode_repo_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RepoPage(
      repos: dco_decode_list_repo(arr[0]),
      nextPage: dco_decode_opt_box_autoadd_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Pipeline> sse_decode_StreamSink_pipeline_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PipelineConclusion sse_decode_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_conclusion(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CiJob sse_decode_ci_job(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_status = sse_decode_pipeline_status(deserializer);
    var var_conclusion = sse_decode_opt_box_autoadd_pipeline_conclusion(
      deserializer,
    );
    return CiJob(
      id: var_id,
      name: var_name,
      status: var_status,
      conclusion: var_conclusion,
    );
  }

  @protected
  CodeportError sse_decode_codeport_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CodeportError_Auth();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return CodeportError_Network(var_field0);
      case 2:
        var var_resetAt = sse_decode_String(deserializer);
        return CodeportError_RateLimited(resetAt: var_resetAt);
      case 3:
        return CodeportError_NotFound();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return CodeportError_Validation(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Commit sse_decode_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sha = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    return Commit(sha: var_sha, message: var_message, author: var_author);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Issue sse_decode_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_number = sse_decode_u_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_state = sse_decode_issue_state(deserializer);
    var var_labels = sse_decode_list_String(deserializer);
    return Issue(
      id: var_id,
      number: var_number,
      title: var_title,
      state: var_state,
      labels: var_labels,
    );
  }

  @protected
  IssueComment sse_decode_issue_comment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    return IssueComment(id: var_id, body: var_body, author: var_author);
  }

  @protected
  IssueState sse_decode_issue_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return IssueState.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CiJob> sse_decode_list_ci_job(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CiJob>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ci_job(deserializer));
    }
    return ans_;
  }

  @protected
  List<Commit> sse_decode_list_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Commit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_commit(deserializer));
    }
    return ans_;
  }

  @protected
  List<Issue> sse_decode_list_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Issue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_issue(deserializer));
    }
    return ans_;
  }

  @protected
  List<IssueComment> sse_decode_list_issue_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IssueComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_issue_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<Pipeline> sse_decode_list_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Pipeline>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Repo> sse_decode_list_repo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Repo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_repo(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PipelineConclusion? sse_decode_opt_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pipeline_conclusion(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pipeline sse_decode_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_status = sse_decode_pipeline_status(deserializer);
    var var_conclusion = sse_decode_opt_box_autoadd_pipeline_conclusion(
      deserializer,
    );
    var var_runNumber = sse_decode_u_64(deserializer);
    return Pipeline(
      id: var_id,
      status: var_status,
      conclusion: var_conclusion,
      runNumber: var_runNumber,
    );
  }

  @protected
  PipelineConclusion sse_decode_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PipelineConclusion.values[inner];
  }

  @protected
  PipelineStatus sse_decode_pipeline_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PipelineStatus.values[inner];
  }

  @protected
  Repo sse_decode_repo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_fullName = sse_decode_String(deserializer);
    var var_private = sse_decode_bool(deserializer);
    var var_stars = sse_decode_u_64(deserializer);
    var var_defaultBranch = sse_decode_String(deserializer);
    return Repo(
      id: var_id,
      fullName: var_fullName,
      private: var_private,
      stars: var_stars,
      defaultBranch: var_defaultBranch,
    );
  }

  @protected
  RepoPage sse_decode_repo_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_repos = sse_decode_list_repo(deserializer);
    var var_nextPage = sse_decode_opt_box_autoadd_u_32(deserializer);
    return RepoPage(repos: var_repos, nextPage: var_nextPage);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_pipeline_Sse(
    RustStreamSink<Pipeline> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_conclusion(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_ci_job(CiJob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_pipeline_status(self.status, serializer);
    sse_encode_opt_box_autoadd_pipeline_conclusion(self.conclusion, serializer);
  }

  @protected
  void sse_encode_codeport_error(CodeportError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CodeportError_Auth():
        sse_encode_i_32(0, serializer);
      case CodeportError_Network(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case CodeportError_RateLimited(resetAt: final resetAt):
        sse_encode_i_32(2, serializer);
        sse_encode_String(resetAt, serializer);
      case CodeportError_NotFound():
        sse_encode_i_32(3, serializer);
      case CodeportError_Validation(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_commit(Commit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sha, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.author, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_issue(Issue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_64(self.number, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_issue_state(self.state, serializer);
    sse_encode_list_String(self.labels, serializer);
  }

  @protected
  void sse_encode_issue_comment(IssueComment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.author, serializer);
  }

  @protected
  void sse_encode_issue_state(IssueState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ci_job(List<CiJob> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ci_job(item, serializer);
    }
  }

  @protected
  void sse_encode_list_commit(List<Commit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_commit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_issue(List<Issue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_issue(item, serializer);
    }
  }

  @protected
  void sse_encode_list_issue_comment(
    List<IssueComment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_issue_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline(List<Pipeline> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_repo(List<Repo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_repo(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pipeline_conclusion(
    PipelineConclusion? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pipeline_conclusion(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pipeline(Pipeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_pipeline_status(self.status, serializer);
    sse_encode_opt_box_autoadd_pipeline_conclusion(self.conclusion, serializer);
    sse_encode_u_64(self.runNumber, serializer);
  }

  @protected
  void sse_encode_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pipeline_status(
    PipelineStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_repo(Repo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.fullName, serializer);
    sse_encode_bool(self.private, serializer);
    sse_encode_u_64(self.stars, serializer);
    sse_encode_String(self.defaultBranch, serializer);
  }

  @protected
  void sse_encode_repo_page(RepoPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_repo(self.repos, serializer);
    sse_encode_opt_box_autoadd_u_32(self.nextPage, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
