// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/auth.dart';
import 'api/cicd.dart';
import 'api/issues.dart';
import 'api/repositories.dart';
import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -701466522;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_codeport',
        ioDirectory: '../../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<Issue>> crateApiIssuesGithubListIssues({
    required String token,
    required String fullName,
    String? state,
  });

  Future<List<Repo>> crateApiRepositoriesGithubListRepos({
    required String token,
    required int page,
  });

  Future<List<Pipeline>> crateApiCicdGithubListRuns({
    required String token,
    required String fullName,
  });

  Future<void> crateApiCicdGithubRetryRun({
    required String token,
    required BigInt runId,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiAuthValidateToken({required String token});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<Issue>> crateApiIssuesGithubListIssues({
    required String token,
    required String fullName,
    String? state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          sse_encode_opt_String(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_issue,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiIssuesGithubListIssuesConstMeta,
        argValues: [token, fullName, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIssuesGithubListIssuesConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_issues",
        argNames: ["token", "fullName", "state"],
      );

  @override
  Future<List<Repo>> crateApiRepositoriesGithubListRepos({
    required String token,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_repo,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiRepositoriesGithubListReposConstMeta,
        argValues: [token, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRepositoriesGithubListReposConstMeta =>
      const TaskConstMeta(
        debugName: "github_list_repos",
        argNames: ["token", "page"],
      );

  @override
  Future<List<Pipeline>> crateApiCicdGithubListRuns({
    required String token,
    required String fullName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(fullName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pipeline,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubListRunsConstMeta,
        argValues: [token, fullName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubListRunsConstMeta => const TaskConstMeta(
    debugName: "github_list_runs",
    argNames: ["token", "fullName"],
  );

  @override
  Future<void> crateApiCicdGithubRetryRun({
    required String token,
    required BigInt runId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_u_64(runId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiCicdGithubRetryRunConstMeta,
        argValues: [token, runId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCicdGithubRetryRunConstMeta => const TaskConstMeta(
    debugName: "github_retry_run",
    argNames: ["token", "runId"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiAuthValidateToken({required String token}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_codeport_error,
        ),
        constMeta: kCrateApiAuthValidateTokenConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthValidateTokenConstMeta =>
      const TaskConstMeta(debugName: "validate_token", argNames: ["token"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PipelineConclusion dco_decode_box_autoadd_pipeline_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_conclusion(raw);
  }

  @protected
  CodeportError dco_decode_codeport_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CodeportError_Auth();
      case 1:
        return CodeportError_Network(dco_decode_String(raw[1]));
      case 2:
        return CodeportError_RateLimited(resetAt: dco_decode_String(raw[1]));
      case 3:
        return CodeportError_NotFound();
      case 4:
        return CodeportError_Validation(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Issue dco_decode_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Issue(
      id: dco_decode_u_64(arr[0]),
      number: dco_decode_u_64(arr[1]),
      title: dco_decode_String(arr[2]),
      state: dco_decode_issue_state(arr[3]),
      labels: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  IssueState dco_decode_issue_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IssueState.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Issue> dco_decode_list_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_issue).toList();
  }

  @protected
  List<Pipeline> dco_decode_list_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Repo> dco_decode_list_repo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_repo).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PipelineConclusion? dco_decode_opt_box_autoadd_pipeline_conclusion(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pipeline_conclusion(raw);
  }

  @protected
  Pipeline dco_decode_pipeline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Pipeline(
      id: dco_decode_u_64(arr[0]),
      status: dco_decode_pipeline_status(arr[1]),
      conclusion: dco_decode_opt_box_autoadd_pipeline_conclusion(arr[2]),
      runNumber: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  PipelineConclusion dco_decode_pipeline_conclusion(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PipelineConclusion.values[raw as int];
  }

  @protected
  PipelineStatus dco_decode_pipeline_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PipelineStatus.values[raw as int];
  }

  @protected
  Repo dco_decode_repo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Repo(
      id: dco_decode_u_64(arr[0]),
      fullName: dco_decode_String(arr[1]),
      private: dco_decode_bool(arr[2]),
      stars: dco_decode_u_64(arr[3]),
      defaultBranch: dco_decode_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PipelineConclusion sse_decode_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_conclusion(deserializer));
  }

  @protected
  CodeportError sse_decode_codeport_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CodeportError_Auth();
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return CodeportError_Network(var_field0);
      case 2:
        var var_resetAt = sse_decode_String(deserializer);
        return CodeportError_RateLimited(resetAt: var_resetAt);
      case 3:
        return CodeportError_NotFound();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return CodeportError_Validation(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Issue sse_decode_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_number = sse_decode_u_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_state = sse_decode_issue_state(deserializer);
    var var_labels = sse_decode_list_String(deserializer);
    return Issue(
      id: var_id,
      number: var_number,
      title: var_title,
      state: var_state,
      labels: var_labels,
    );
  }

  @protected
  IssueState sse_decode_issue_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return IssueState.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Issue> sse_decode_list_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Issue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_issue(deserializer));
    }
    return ans_;
  }

  @protected
  List<Pipeline> sse_decode_list_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Pipeline>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Repo> sse_decode_list_repo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Repo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_repo(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PipelineConclusion? sse_decode_opt_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pipeline_conclusion(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pipeline sse_decode_pipeline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_status = sse_decode_pipeline_status(deserializer);
    var var_conclusion = sse_decode_opt_box_autoadd_pipeline_conclusion(
      deserializer,
    );
    var var_runNumber = sse_decode_u_64(deserializer);
    return Pipeline(
      id: var_id,
      status: var_status,
      conclusion: var_conclusion,
      runNumber: var_runNumber,
    );
  }

  @protected
  PipelineConclusion sse_decode_pipeline_conclusion(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PipelineConclusion.values[inner];
  }

  @protected
  PipelineStatus sse_decode_pipeline_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PipelineStatus.values[inner];
  }

  @protected
  Repo sse_decode_repo(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_fullName = sse_decode_String(deserializer);
    var var_private = sse_decode_bool(deserializer);
    var var_stars = sse_decode_u_64(deserializer);
    var var_defaultBranch = sse_decode_String(deserializer);
    return Repo(
      id: var_id,
      fullName: var_fullName,
      private: var_private,
      stars: var_stars,
      defaultBranch: var_defaultBranch,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_conclusion(self, serializer);
  }

  @protected
  void sse_encode_codeport_error(CodeportError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CodeportError_Auth():
        sse_encode_i_32(0, serializer);
      case CodeportError_Network(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case CodeportError_RateLimited(resetAt: final resetAt):
        sse_encode_i_32(2, serializer);
        sse_encode_String(resetAt, serializer);
      case CodeportError_NotFound():
        sse_encode_i_32(3, serializer);
      case CodeportError_Validation(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_issue(Issue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_64(self.number, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_issue_state(self.state, serializer);
    sse_encode_list_String(self.labels, serializer);
  }

  @protected
  void sse_encode_issue_state(IssueState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_issue(List<Issue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_issue(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline(List<Pipeline> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_repo(List<Repo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_repo(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pipeline_conclusion(
    PipelineConclusion? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pipeline_conclusion(self, serializer);
    }
  }

  @protected
  void sse_encode_pipeline(Pipeline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_pipeline_status(self.status, serializer);
    sse_encode_opt_box_autoadd_pipeline_conclusion(self.conclusion, serializer);
    sse_encode_u_64(self.runNumber, serializer);
  }

  @protected
  void sse_encode_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_pipeline_status(
    PipelineStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_repo(Repo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.fullName, serializer);
    sse_encode_bool(self.private, serializer);
    sse_encode_u_64(self.stars, serializer);
    sse_encode_String(self.defaultBranch, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
