// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/auth.dart';
import 'api/cicd.dart';
import 'api/issues.dart';
import 'api/repositories.dart';
import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PipelineConclusion dco_decode_box_autoadd_pipeline_conclusion(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CiJob dco_decode_ci_job(dynamic raw);

  @protected
  CodeportError dco_decode_codeport_error(dynamic raw);

  @protected
  Commit dco_decode_commit(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Issue dco_decode_issue(dynamic raw);

  @protected
  IssueComment dco_decode_issue_comment(dynamic raw);

  @protected
  IssueState dco_decode_issue_state(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CiJob> dco_decode_list_ci_job(dynamic raw);

  @protected
  List<Commit> dco_decode_list_commit(dynamic raw);

  @protected
  List<Issue> dco_decode_list_issue(dynamic raw);

  @protected
  List<IssueComment> dco_decode_list_issue_comment(dynamic raw);

  @protected
  List<Pipeline> dco_decode_list_pipeline(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Repo> dco_decode_list_repo(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PipelineConclusion? dco_decode_opt_box_autoadd_pipeline_conclusion(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Pipeline dco_decode_pipeline(dynamic raw);

  @protected
  PipelineConclusion dco_decode_pipeline_conclusion(dynamic raw);

  @protected
  PipelineStatus dco_decode_pipeline_status(dynamic raw);

  @protected
  Repo dco_decode_repo(dynamic raw);

  @protected
  RepoPage dco_decode_repo_page(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PipelineConclusion sse_decode_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CiJob sse_decode_ci_job(SseDeserializer deserializer);

  @protected
  CodeportError sse_decode_codeport_error(SseDeserializer deserializer);

  @protected
  Commit sse_decode_commit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Issue sse_decode_issue(SseDeserializer deserializer);

  @protected
  IssueComment sse_decode_issue_comment(SseDeserializer deserializer);

  @protected
  IssueState sse_decode_issue_state(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CiJob> sse_decode_list_ci_job(SseDeserializer deserializer);

  @protected
  List<Commit> sse_decode_list_commit(SseDeserializer deserializer);

  @protected
  List<Issue> sse_decode_list_issue(SseDeserializer deserializer);

  @protected
  List<IssueComment> sse_decode_list_issue_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<Pipeline> sse_decode_list_pipeline(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Repo> sse_decode_list_repo(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PipelineConclusion? sse_decode_opt_box_autoadd_pipeline_conclusion(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Pipeline sse_decode_pipeline(SseDeserializer deserializer);

  @protected
  PipelineConclusion sse_decode_pipeline_conclusion(
    SseDeserializer deserializer,
  );

  @protected
  PipelineStatus sse_decode_pipeline_status(SseDeserializer deserializer);

  @protected
  Repo sse_decode_repo(SseDeserializer deserializer);

  @protected
  RepoPage sse_decode_repo_page(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ci_job(CiJob self, SseSerializer serializer);

  @protected
  void sse_encode_codeport_error(CodeportError self, SseSerializer serializer);

  @protected
  void sse_encode_commit(Commit self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_issue(Issue self, SseSerializer serializer);

  @protected
  void sse_encode_issue_comment(IssueComment self, SseSerializer serializer);

  @protected
  void sse_encode_issue_state(IssueState self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ci_job(List<CiJob> self, SseSerializer serializer);

  @protected
  void sse_encode_list_commit(List<Commit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_issue(List<Issue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_issue_comment(
    List<IssueComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pipeline(List<Pipeline> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_repo(List<Repo> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_pipeline_conclusion(
    PipelineConclusion? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline(Pipeline self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_conclusion(
    PipelineConclusion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pipeline_status(
    PipelineStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_repo(Repo self, SseSerializer serializer);

  @protected
  void sse_encode_repo_page(RepoPage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
